### ISSUE TITLE
Z-index of overlay

### ISSUE THREAD

**Issue by taalas** [gasparesganga/jquery-popup-window#1]
Hi!
While using your (excellent) popup plugin I sometimes run into problems with elements having a higher z-order than the overlay element making it possible to interact with them although the window should be modal. Is there anything I can do to change that behaviour?

**Comment by gasparesganga** [comment]
Hi!
When I designed this plugin I didn't consider that common behaviour of some plugins/programmers to rely on z-index instead of DOM placement.
A very quick fix for your current projects should be as simple as adding an explicit `z-index` for class `.popupwindow_container` to your CSS (it can be any CSS file in your project):
```css
.popupwindow_container {
    z-index : 9999;  /* I used 9999 here but you can use whatever value is bigger that the other elements in your page /*
}
```
